### ISSUE TITLE
Add a date/time picker

### ISSUE THREAD

**Issue by maestrofjp** [maestrofjp/Enlist-Grails#18]
Something like this for date, but doesn't have time:
http://aymkdn.github.com/Datepicker-for-Bootstrap/

If you need time, probably this:
http://jdewit.github.com/bootstrap-timepicker/

Something like this is nice for ranges if you don't need dates (i.e. search activities over range of days, etc):
http://www.dangrossman.info/2012/08/20/a-date-range-picker-for-twitter-bootstrap/

**Comment by maestrofjp** [comment]
@mpwoodward and @kwiersma, what do you think about using the first two -- a date picker and a separate time picker for activities?

**Comment by kwiersma** [comment]
I like the first and second ones.

**Comment by maestrofjp** [comment]
I'll pull them into the project.  I assume I just dump them into the web-app/js folder since they are not Grails plugins and then add them to the bootstrap.gsp head area?

**Comment by maestrofjp** [comment]
I committed this and didn't make the right comment
