### ISSUE TITLE
Volunteers are authorized to add events but not add Users to them.

### ISSUE THREAD

**Issue by JacobASeverson** [maestrofjp/Enlist-Grails#22]
Is this intended? If so, the "Add User" link should be removed from the Create Event screen.

**Comment by maestrofjp** [comment]
Roles hasn't been rolled into the navigation or checked in controllers yet.  Feel free to do that.

Yes, you're right - volunteers shouldn't be able to add events or activities -- just people with coordinator or administrator status.  The roles aren't that fine grained at the moment -- just trying to get some there and rework as necessary.

**Comment by JacobASeverson** [comment]
After looking around a bit more I figured that was the case. I could start looking into that.

**Comment by JacobASeverson** [comment]
Closing for old issues cleanup.
