### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by JacobASeverson** [maestrofjp/Enlist-Grails#23]
I'm trying to add unit testing to all the current models and controllers but am running into some error that says

 Error Compilation error compiling [unit] tests: startup failed:
/home/midwest-meat/Documents/repos/Enlist-Grails/test/unit/enlist/GrailsActivityControllerTests.groovy: 11: Only classes and closures can be used for attribute 'value' in @grails.test.mixin.TestFor
 @ line 11, column 10.
   @TestFor(GrailsActivityController)
            ^

1 error
 (Use --stacktrace to see the full trace)

Does anyone see this when they try to run the ActivityControllerTests?

**Comment by maestrofjp** [comment]
Hrm, I don't think I've run the run-tests option yet.

**Comment by beckje01** [comment]
Tests should be working now.

**Comment by JacobASeverson** [comment]
Closing for old issues cleanup.
